### ISSUE TITLE
Update the main readme.md file

### ISSUE THREAD

**Issue by hardik-thapar** [Abishethvarman/HNDIT3032-Data-Structures-and-Algorithms#6]
Hi @Abishethvarman sir,
I am a beginner in the world of open source and I would like to request you to kindly allow me to contribute to your project for hacktoberfest.
The main readme.md file should be updated and information regarding the project should be added to it. It should contain the details regarding the topic of the project and what sub topics they cover. I want to request you to kindly assign me this task.
 Thanks for your time.
  Kindly assign me this issue under Hacktoberfest 2024.

**Comment by Abishethvarman** [comment]
@hardik-thapar, sorry this repo is only for the  SLIATE Batticaloa HNDIT 2nd Year Part time students.
The PR from outside wont e accepted. Hope you understand. You'll get hacktoberfest repo for sure.
