### ISSUE TITLE
Update readme.md for Vector

### ISSUE THREAD

**Issue by hardik-thapar** [Abishethvarman/HNDIT3032-Data-Structures-and-Algorithms#8]
Hi @Abishethvarman sir,
I would like to request your permission to update the readme.md file for the Vector topic, as it should have a readme.md file where the information regarding the topics, a brief explanation and the practice questions are available. This will ensure that people can the understand and learn from this file.
Kindly assign me this issue under Hacktoberfest 2024.

**Comment by Abishethvarman** [comment]
@hardik-thapar, sorry this repo is only for the  SLIATE Batticaloa HNDIT 2nd Year Part time students.
The PR from outside wont e accepted. Hope you understand. You'll get hacktoberfest repo for sure.
